name: i_need_help
description: Getting and recieving help

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+2
  cupertino_icons: ^0.1.2
  dropdownfield: 1.0.0

flutter:
  uses-material-design: true