version: "3.4"
services:
  db:
    image: postgres:10
    container_name: db
    env_file:
    - ./.env
  api:
    build: .
    container_name: api
    env_file:
    - ./.env
    volumes:
      - ./src:/code
    command: /gunicorn.sh
    depends_on:
      - db
    ports:
      - "80:80"