# Generated by Django 2.2.6 on 2019-11-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191102_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='1970-01-01', help_text='Enter your birthday.', verbose_name='birthday'),
            preserve_default=False,
        ),
    ]
