# Generated by Django 2.2.6 on 2019-11-02 21:10

import accounts.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, help_text='Enter a valid email. If you are a current IYNA staff member, do not use your @youthneuro.org account.', max_length=255, unique=True, verbose_name='email')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user can log in.', verbose_name='active?')),
                ('is_staff', models.BooleanField(default=False, help_text='Can this user log in to the admin panel.', verbose_name='staff?')),
                ('is_superuser', models.BooleanField(default=False, help_text='Does this user have access to all permissions.', verbose_name='admin?')),
                ('fname', models.CharField(help_text='Enter your first name.', max_length=30, verbose_name='First Name')),
                ('lname', models.CharField(help_text='Enter your last name.', max_length=150, verbose_name='Last Name')),
                ('birthday', models.DateField(help_text='Enter your birthday.', null=True, verbose_name='birthday')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='When did this user join?', verbose_name='Date Joined')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
