# Generated by Django 2.2.6 on 2019-11-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helprequest',
            old_name='description',
            new_name='item_description',
        ),
        migrations.AddField(
            model_name='helprequest',
            name='item',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helprequest',
            name='severity_detail',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
