# Generated by Django 2.2.6 on 2019-11-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20191103_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='severity',
            field=models.IntegerField(),
        ),
    ]
